version: '3.9'

services:
  app:
    build: .
    container_name: php-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: challenge
    ports:
     - "5433:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5673:5672"
      - "15672:15672"
    networks:
      - app-network
    volumes:
      - "./rabbitmq/logs:/var/log/rabbitmq:rw"

  nginx:
    image: nginx:alpine
    container_name: php-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  database_data:
