parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Action\:
        resource: '../src/Action'
        tags: [ 'controller.service_arguments' ]

    App\Infrastructure\Service\TransactionAuthorizer\TransactionAuthorizerService:
        arguments:
             $baseUrl: '%env(resolve:TRANSACTION_AUTHORIZER_URL)%'
